### PR TITLE
Increased interactivity with handles and forwards

### LINKED ISSUE #47: Editable forwards
- [x] Forwards can be deleted
- [x] Type of forward can be adjusted (Succes, failure, exception)

### PR DESCRIPTION
**Pull request by Daan0709**
- You can now detach forwards by dragging them near their source or target handle
- Source handles can only have 1 forward originating from them
- Can change the type of the handle, which also changes the label of the forward

Closes #47

### CODE REVIEW

File: src/main/react/app/routes/builder/canvas/nodetypes/frank-node.tsx [hunk 1]
```diff
@@ -108,11 +106,19 @@ export default function FrankNode(properties: NodeProps<FrankNode>) {
     setIsContextMenuOpen(false)
   }
 
+  const changeHandleType = (handleIndex: number, newType: string) => {
+    useFlowStore.getState().updateHandle(properties.id, handleIndex, { type: newType, index: handleIndex })
+    // Timeout to prevent bug from edgelabel not properly updating
+    setTimeout(() => {
+      updateNodeInternals(properties.id)
+    }, 0)
```
Comment (philipsens) [inline src/main/react/app/routes/builder/canvas/nodetypes/frank-node.tsx:114]: I think you can remove the `0`.
