### PR TITLE
Various fixes

### LINKED ISSUE #259: Filter out empty configurations and .xml files that are not configurations from the configuration manager

### LINKED ISSUE #260: Remove '+' handle when an element already has a maximum amount of handles

### PR DESCRIPTION
**Pull request by Daan0709**
- Add handle button is now removed if all available forward types of an element already have a handle.
- If a custom forward/handle is possible, the add handle button stays regardless if a custom handle is already present.
- .xml files without any adapters in them now no longer show up in the configuration manager page.
- Added a search function to the configuration manager page
- Fixed an issue with the projectlanding action buttons looking weird on lower resolution screens

Closes #259, Closes #260

### CODE REVIEW

File: src/main/frontend/app/routes/configurations/configuration-manager.tsx [hunk 1]
```diff
@@ -106,7 +111,66 @@ export default function ConfigurationManager() {
...
+
+  useEffect(() => {
+    if (!currentProject?.name || configFiles.length === 0) {
+      setFilesWithAdapters([])
+      return
+    }
+
+    let cancelled = false
+
+    const loadAdapters = async () => {
```
Comment (Matthbo) [inline src/main/frontend/app/routes/configurations/configuration-manager.tsx]: Please put a comment on this saying it'll run in the background
